services:
  storage:
    build: ./Storage
    volumes:
      - storageVolume:/logs
    ports:
      - "8080:8080"
  
  service2:
    build: ./Service2
    volumes:
      - ./vStorage:/vStorage
    ports:
      - "8090:8090"
    depends_on:
      - storage
  
  service1:
    build: ./Service1
    volumes:
      - ./vStorage:/vStorage
    ports:
      - "8070:8070"
    depends_on:
      - service2
      - storage

volumes:
  storageVolume:
    name: storageVolume